language: bash
sudo: false
install: true
addons:
  apt:
    packages:
    - lua5.1
    - python2.7
script: "./build.sh web"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: gfI4KTCBUJ6lzK4KN1/GPqnQngq5I1+cSHBQ3Onmr5jiu363cE2bT+WMNPr1lnLdJe89/vNh0uFhug24PHG+K2BMdxneD3FIKwEPsqSE4WW0hWce22RoGKTn/b1v11tNXi2BReI4zpbliAuSaRtM+SKBceqvii1P4EV1n3BWv8lV6YhYKrcMqiz+H5QHqmfY7pkahdCet9+L4zm1NkFw80XLjoAmbOGh97IWOKNT5803tqkbFYg22iiS7ikexntNfWOVBYvwL/KHJUsbNPVjwEEBbZfFHeZKwnDXsgqCgHbX25f9SFUOD9FQoKCnnioUfPNyLQn+Dk2mK1L+JE/IBCqDY7eKe9JulX3x1yVAy56PPgWslmiCMLaih0zCLv/3r0OoC+zV/1vE2X+VbvhRtSdCG4qJ0GqCqmAQlgLaDnDG0X5hnl2MZ2OpmBZfsnmu56wtf4svIp4drTCuab5a+GbrgSWE9rEihGO8AxUAIQkv50SRlhZCo+TR2pMgokHeOA4YG72b5yK6W5oRx0F3s2hlzwFwmTeYlU1VCq0nlsL79JWfjQL1JgjprvpcCGlYKuDL6vY+BZQl4x0z2+0dw/j1H7xGJFVs6Rvj92tNZs0KxoXU39rqQS89yYZ4hlXCzulR2H8SiZpYzCDLGtP7BSjDrq6sC8uL/1AWNQZyh1k=
  file:
  - target/64pixels.love
  - target/64pixels-win.zip
  - target/64pixels-web.zip
  on:
    tags: true
    all_branches: true
after_success:
  - "[[ -n $TRAVIS_TAG ]] && ./build.sh deploy premek/64pixels"
env:
  global:
    - secure: R6lRUgY4gphBigptj5AKfYB5cTds/U4hNrSCJkisHYADcn1qQncdqZ8e3ZLJe2w/WFcOhZLVlLsL8k+0T/mQa9fSgzgdQJLrl0Ub0LF+1EbQDnnbfcCxI7mAm10jCVzP1AGuMQql3qO8dgr3UwbvlbFfQNMRS5+HZz7XRBFyyUQyBONs88lZF4CADWK6yYBu/SysmU9uKEjijRWz9BqA4JpHTEvIUooR1siwdlYTnnrepVvDSlq66/LdNs02Gv8erKp22Ehni1EMTpMDQf7lJ5HDJw6tmR1G2sk6ug+lFfSwyGLJbvomQ2C/aMHM1IZxcYbtlET18YEQQww6KNwMHMUir7GaqV8gM1ICLRh5X7deVMxvSgbKSN5Vx8HtM1ZWM4fRSc74dgJ6th7Meo091w2plSdmZfNpDoZZPaV9HFylWB5SJzCESmasOIVZtOgX6i+Jv62ji/n4LqpG91wB61JjfiX2Ubql8d4/43JBMODA9jWy3l+zD4ugkAopIL8p3sTsdgdLBsnfircx9fj+Eu9rRuedaTlfYYEggPur/8zQEXxT0USMoRb15x5ITNMXQGwcI2//l9JBIE+xUCw3/NxWw3s6AENw7NiF23kENyyPaWF6/mKWnOcc191NiR8XhnGAd+qkXguURkAlNrgR/azsK2LNslGPTUpHL/Po7iA=

# curl -u premysl.vyhnal@gmail.com   -d '{"scopes":["public_repo"],"note":"XXX token name XXX"}'   https://api.github.com/authorizations
# travis encrypt GH_TOKEN=<token> --add
